services:
  postgres:
    image: postgres:16-alpine
    container_name: scu-canteen-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: scu_admin
      POSTGRES_PASSWORD: scu_canteen_2026
      POSTGRES_DB: scu_canteen
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
